# Your Solution
services:

  book-catalog:
    image: vk4041.azurecr.io/book-catalog:1
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
     - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://vk4041_koyo_user:ZbMTJMPgAouLPdyytKd9KOwBZDzIN0IU@dpg-crj4hjtumphs73csteeg-a.singapore-postgres.render.com/vk4041_koyo
    restart: "no"

  inventory_management:
    image: vk4041.azurecr.io/inventory_management:1
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
     - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://vk4041_koyo_user:ZbMTJMPgAouLPdyytKd9KOwBZDzIN0IU@dpg-crj4hjtumphs73csteeg-a.singapore-postgres.render.com/vk4041_koyo
    restart: "no"
