# Your Solution
#Run using kubectl apply -f scripts/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk4041
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vk4041
  template:
    metadata:
      labels:
        app: vk4041
    spec:
      containers:
      - name: book-catalog
        image: vk4041.azurecr.io/book-catalog:1
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: DATABASE_URL
          value: postgresql://vk4041_koyo_user:ZbMTJMPgAouLPdyytKd9KOwBZDzIN0IU@dpg-crj4hjtumphs73csteeg-a.singapore-postgres.render.com/vk4041_koyo
      - name: inventory-management
        image: vk4041.azurecr.io/inventory_management:1
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        - name: DATABASE_URL
          value: postgresql://vk4041_koyo_user:ZbMTJMPgAouLPdyytKd9KOwBZDzIN0IU@dpg-crj4hjtumphs73csteeg-a.singapore-postgres.render.com/vk4041_koyo

---
apiVersion: v1
kind: Service
metadata:
  name: vk4041
spec:
  selector:
    app: vk4041
  ports:
    - name: book-catalog
      port: 8000
      targetPort: 8000
    - name: inventory-management
      port: 8001
      targetPort: 8001
  type: LoadBalancer
